services:

  kumcer-service:
    image: kumcer-api
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - path: .env
        required: true
  database:
    image: postgres:alpine
    ports:
      - "5445:5432"
    env_file:
      - path: .env
        required: true
    volumes:
      - pgdata:/var/lib/postgresql/kumcerdata
volumes:
  pgdata: